version: '3.8'

services:
  web:
    build: .
    container_name: django_api
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app
    working_dir: /app/portal_15  # Set correct working directory
