# Generated by Django 5.1.7 on 2025-03-28 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('donation_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
